version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-linux:
    executor: docker/docker
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up Docker Buildx
          # docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          # docker buildx inspect --bootstrap
          command: |
            docker buildx create --name crossbuilder --use
      - docker/check:
          docker-username: DOCKER_USERNAME
      - docker/build:
          image: verdigristech/localproxy
          use-buildkit: true
          extra_build_args: --platform=linux/amd64,linux/arm64,linux/arm --progress=plain

workflows:
  release:
    jobs:
      - build-linux:
          context: dockerhub
