version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build:
    parameters:
      platform:
        type: string
        default: linux/amd64
      resource_class:
        type: string
        default: medium
    executor: docker/docker
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --name crossbuilder --use
      - docker/check:
          docker-username: DOCKER_USERNAME
      - docker/build:
          image: verdigristech/localproxy
          use-buildkit: true
          extra_build_args: --platform=<< parameters.platform >> --progress=plain

workflows:
  release:
    jobs:
      - build:
          context: dockerhub
          matrix:
            parameters:
              platform:
                - linux/arm64,linux/arm/v7
                - linux/amd64
              resource_class:
                - arm.large
                - large
            # Build optimization: don't build ARM images with x86_64 runners and vice versa
            exclude:
              - linux/arm64,linux/arm/v7: large
              - linux/amd64: arm.large
