version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-linux:
    parameters:
      architecture:
        type: string
        default: amd64
      resource-class:
        type: string
        default: medium
    executor: docker/docker
    resource_class: << parameters.resource-class >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --name crossbuilder --use
      - docker/check:
          docker-username: DOCKER_USERNAME
      - docker/build:
          image: verdigristech/localproxy
          use-buildkit: true
          extra_build_args: --platform=linux/<< parameters.architecture >> --progress=plain

workflows:
  release:
    jobs:
      - build-linux:
          context: dockerhub
          matrix:
            parameters:
              architecture:
                - "arm64"
                - "arm/v7"
                - "amd64"
              resource-class:
                - arm.large
                - large
            # Build optimization: don't build ARM images with x86_64 runners and vice versa
            exclude:
              - arm64: large
              - arm/v7: large
              - amd64": arm.large
