version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build-linux:
    parameters:
      architecture:
        type: string
        default: amd64
      variant:
        type: string
        default: ""
      resource-class:
        type: string
        default: medium
      local-cache-prefix:
        type: string
        default: docker-buildx-localproxy
      local-cache-path:
        type: string
        default: /tmp/buildx-cache
    executor: docker/docker
    resource_class: << parameters.resource-class >>
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - << parameters.local-cache-prefix >>-{{ arch }}-{{ .Branch }}
            - << parameters.local-cache-prefix >>-{{ arch }}-
      - run:
          name: Set up environment variables
          command: |
            echo "export ARCH=<< parameters.architecture >>" >> $BASH_ENV
            echo "export VARIANT=<< parameters.variant >>" >> $BASH_ENV
      - run:
          name: Set up Docker Buildx context
          command: docker buildx create --name crossbuilder --use
      - docker/check:
          docker-username: DOCKER_USERNAME
      - docker/build:
          image: verdigristech/localproxy
          use-buildkit: true
          extra_build_args: |
            --platform="linux/$(printf '%s%s' "${ARCH}" "${VARIANT:+/VARIANT}")" --progress=plain --cache-from=type=local,src=<< parameters.local-cache-path >> --cache-to=type=local,mode=max,dest=<< parameters.local-cache-path >> --output=type=tar,dest=localproxy-linux-${ARCH}${VARIANT}.tar
      - save_cache:
          paths:
            - << parameters.local-cache-path >>
          key: << parameters.local-cache-prefix >>-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.local-cache-path >>/index.json" }}
      - store_artifact:
          path: localproxy-linux-<< parameters.architecture >><< parameters.variant >>.tar

workflows:
  release:
    jobs:
      - build-linux:
          context: dockerhub
          name: build-linux-amd64
          architecture: amd64
          resource-class: large
      - build-linux:
          context: dockerhub
          name: build-linux-arm64
          architecture: arm64
          resource-class: arm.large
      - build-linux:
          context: dockerhub
          name: build-linux-armv7
          architecture: arm
          variant: v7
          resource-class: arm.large
